# Generated by Django 4.2.10 on 2024-02-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('resume', models.FileField(upload_to='uploads/')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
    ]
