# Generated by Django 4.2.10 on 2024-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_location_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
